services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    image: dhruvthak3r/probe
    container_name: probe
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8181:8080"

  probe-ui:
    image: dhruvthak3r/probe-ui
    container_name: probe-ui
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "3000:80"

volumes:
  mysql_data: